version: '3'

services:
  server:
    environment:
      - DEBUG=0
    restart: always
  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: "${MANAGEMENT_API_SECRET}"
        databases:
          default:
            connector: postgres
            host: "${DB_HOST}"
            port: "${DB_PORT}"
            database: "${DB_NAME}"
            user: "${DB_USER}"
            password: "${DB_PASSWORD}"
            rawAccess: true
            migrations: true # Remove after Prod Release
            ssl: true

#   prisma:
#     image: prismagraphql/prisma:1.13
#     restart: always
#     expose:
#       - '4466'
#   mysql:
#     restart: always

# volumes: mysql:
